### PR TITLE
DevOps: Precommit

### PR DESCRIPTION
**Pull request by avisionh**
# Summary
This branch implements DevOps best practice in adding automated checks that are run before each commit. It uses the [precommit](https://github.com/lorenzwalthert/precommit) package to achieve this.

Please see the motivating example below for this change:
> Claude is working on a project to connect to the Facebook API and show his profile and updates on a dashboard with Antoinette.
> To connect to the Facebook API, Claude needs to sign-up and use a secret token generated for his account.
> As this token is stored as a file on his computer and he is using it for this project, he stores it in the repo.
> Given that this token allows access to his account, Claude should not reveal it to anyone else.
> - This includes not storing and publishing it on the repo.
> - Ideally, he should either not store the secret token in the repo or she should add it to the `.gitignore` file.
>
> Claude does some work to connect to the Facebook API and saves his progress.
> He also commits and pushes this work and all the other files he has changed, including the file with his secret token on.
> His secret token is now on the public repo for anyone to see, steal and hack into his Facebook profile.

`precommit` works by running some checks when you are (*git*) committing your progress. If these checks fail, then your work is not committed. You will have to change your code to meet these checks before your work can be committed. This means that if you have a pre-commit check that identifies the existence of secrets like an API token, then you will not end up accidentally committing it and consequently, avoid publishing it.

# Changes
The changes made in this PR are:
1. Set-up pre-commit on the project.

***

# Check
- [x] You can install the pre-commit onto your machine.
- [ ] When you make a test change and try to commit it, the pre-commit checks are triggered.
- [ ] The pre-commit checks work when using GitHub desktop.

***

## Installation
To install and use pre-commit, follow instructions below:

``` r
install.packages("precommit")
```

To access pre-commit functionality from R, you also need to install the
[pre-commit framework](https://pre-commit.com). The following command
line methods are tested to work with this R package:

  - `$ pip install pre-commit --user` (macOS, Linux and Windows)
    **outside** a conda or virtual environment.

  - `$ brew install pre-commit` (macOS).

Alternatively, you can handle the installation from R using
[miniconda](https://docs.conda.io/en/latest/miniconda.html):

  - install miniconda if you don’t have it already:
    `reticulate::install_miniconda()`. This needs reticulate \>= 1.14.

  - install the pre-commit framework with
    `precommit::install_precommit()` into the conda environment
    `r-precommit`.

# Note
We have not yet implemented the check to prevent secret tokens being published. This will be the job of a future PR.

This branch is rebased off `devops/package-dependency` so some of the file changes currently seen in this branch are not actually relevant. They will disappear when #2 gets merged into the `main` branch.

A successful pre-commit looks like this:
image

### CODE REVIEW

**Comment by avisionh** [comment]
[Set up DevOps best practice for traffic collisions repo](https://trello.com/c/9XgehCqH/31-set-up-devops-best-practice-for-traffic-collisions-repo)

**Comment by avisionh** [comment]
Would be interested to know if this also works on GitHub desktop.

**Comment by martinctc** [comment]
> Would be interested to know if this also works on GitHub desktop.

No checks are triggered when committing via GitHub desktop, so we'll need to use git CLI I think!

**Comment by martinctc** [comment]
So finally got this to work for me, but (A) it didn't work on GitHub Desktop, and (B) I've had to run `pre-commit install` in the project directory to get this to work:

image

**Review by martinctc — APPROVED** [review]

**Pull request merged**
